# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pip install -e .
            python3 tests/test_datetime_parser.py
          name: run_tests

  python_lint:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            sudo pip install black
      - run:
          command: black . --check --diff
          name: run_black

# Orchestrate or schedule a set of jobs
workflows:
  main:
    jobs:
      - build
      - python_lint
